Phonebook/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [    
    path('', views.home_view, name='home'),
    path('save_contact/', views.save_contact, name='save_contact'),
]

contacts/models.py
from django.db import models

class State(models.Model):
    new_name    = models.CharField(max_length=200)
    new_phone   = models.IntegerField()
    new_email   = models.EmailField()
    
    timestamp           = models.DateTimeField(auto_now_add=True)

contacts/views.py
from django.shortcuts import render

from django.http import HttpResponse, JsonResponse

from .models import State

import json

# from .models import Game, Mode, State

import json

def home_view(request):

    return render(request, "contacts/phonebook.html", {})

def save_contact(request):
    
    data = json.loads(request.body)
    new_name = data['new_name']
    new_phone = data['new_phone']
    new_email = data['new_email']

                
    state = State(new_name=new_name, new_phone=new_phone, new_email=new_email)
    state.save()
    return HttpResponse('hi')

contacts/templates/contacts/phonebook.html
{% load static %}
<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js" type="text/javascript"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'contacts/css/main.css' %}">

    </head>
        <header>

            <h1>Simulizi</h1>

            <nav>
                    <button id="view_contacts">Contacts</button>
                    <button id="messages">Messages</button>
                    <button id="new_contact">Add Contact</button>
            </nav>
        </header>
  


        <main>
            <div class="contacts_display">

            </div>

        </main>

            <div class="newcontact_modal">

                <button class="close_modal" id="close_newcontact_modal">+</button>

                <span>New Contact</span>

                <input id="new_name" placeholder="Name" type="text"></input>
                <input id="new_phone" placeholder="Phone" type="number"></input>
                <input id="new_email" placeholder="E-mail" type="email"></input>
                <input placeholder="Birthday" type="date"></input>
                <input placeholder="Website" type="url"></input>

                <button id="save_contact_btn">Save</button>

            </div>
             

            <script>

                let new_name = document.querySelector('#new_name')
                let new_phone = document.querySelector('#new_phone')
                let new_email = document.querySelector('#new_email')
            
                save_contact_btn.onclick = function() {        
                    axios.post("{% url 'home:save_contact' %}",
                            {
                                new_name: new_name,
                                new_phone: new_phone,
                                new_email: new_email,
                            }, {
                                headers: {
                                    "X-CSRFToken": "{{ csrf_token }}"
                                }
                            }
                        ).then(function(response) {
                        })
                }

                new_contact = document.querySelector('#new_contact')
                close_newcontact = document.querySelector('#close_newcontact_modal')
                save_contact_btn = document.querySelector('#save_contact_btn')

                new_contact.onclick = function(){
                    document.querySelector(".newcontact_modal").style.display = "flex";  
                }
                close_newcontact.onclick = function(){
                    document.querySelector(".newcontact_modal").style.display = "none";  
                }
                    
                function newcontact_modal() {
                    document.querySelector(".newcontact_modal").style.display = "flex";  
                }
                                           
            </script>

        </body>
</html>